// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Topbar from "@/components/layout/Topbar";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "FlyFinder",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Topbar />
//         {children}
//         <Toaster richColors closeButton position="top-right" />
//       </body>
//     </html>
//   );
// }

import './globals.css';
import { ReactNode } from 'react';
import { Metadata } from 'next';
import Navigation from '@/components/navigation/Navigation';

export const metadata: Metadata = {
  title: 'FlySmart - Flight Recommendation System',
  description: 'Find the best flight deals tailored to your preferences',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-blue-50 to-white min-h-screen">
        <Navigation />
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="bg-blue-800 text-white py-6 mt-12">
          <div className="container mx-auto px-4 text-center">
            <p>© {new Date().getFullYear()} FlySmart. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}